# Generated by Django 3.0.5 on 2020-04-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название:')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город:')),
                ('logo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Логотипчик:')),
                ('description', models.TextField(blank=True, max_length=50, null=True, verbose_name='Информация о компании:')),
                ('employee_count', models.IntegerField(blank=True, null=True, verbose_name='Количество сотрудников :')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код:')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название:')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город:')),
                ('picture', models.CharField(blank=True, max_length=50, null=True, verbose_name='Картинка:')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название:')),
                ('skills', models.TextField(blank=True, max_length=50, null=True, verbose_name='Навыки:')),
                ('description', models.TextField(blank=True, max_length=50, null=True, verbose_name='Описание:')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от:')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до:')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано:')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies', to='web.Company', verbose_name='Компания:')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies', to='web.Specialty', verbose_name='Специализация:')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at', 'title'],
            },
        ),
    ]
