# Generated by Django 3.0.5 on 2020-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='Опубликовано:'),
        ),
    ]
