# Generated by Django 3.0.5 on 2020-04-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200409_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(null=True, verbose_name='Опубликовано:'),
        ),
    ]
