# Generated by Django 3.0.5 on 2020-04-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200409_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
