# Generated by Django 3.0.5 on 2020-04-10 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_delete_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название:')),
                ('skills', models.TextField(blank=True, max_length=50, null=True, verbose_name='Навыки:')),
                ('description', models.TextField(blank=True, max_length=50, null=True, verbose_name='Описание:')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от:')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до:')),
                ('published_at', models.DateField(null=True, verbose_name='Опубликовано:')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies', to='web.Company', verbose_name='Компания:')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies', to='web.Specialty', verbose_name='Специализация:')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at', 'title'],
            },
        ),
    ]
