# Generated by Django 3.0.5 on 2020-04-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='location',
        ),
    ]
